
using Newtonsoft.Json;
using System.Collections.Generic;
using YoutubeMusicApi.Models.Generated;

namespace YoutubeMusicApi.Models.AutoGenerated
{
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class Accessibility
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityData accessibilityData { get; set; }
    }

    public class AccessibilityData
    {
        [JsonProperty("label")]
        public string label { get; set; }

        [JsonProperty("accessibilityData")]
        public AccessibilityData accessibilityData { get; set; }
    }

    public class AccessibilityPauseData
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityData accessibilityData { get; set; }
    }

    public class AccessibilityPlayData
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityData accessibilityData { get; set; }
    }

    public class AddToToastAction
    {
        [JsonProperty("item")]
        public Item item { get; set; }
    }

    public class Background
    {
        [JsonProperty("verticalGradient")]
        public VerticalGradient verticalGradient { get; set; }

        [JsonProperty("musicThumbnailRenderer")]
        public MusicThumbnailRenderer musicThumbnailRenderer { get; set; }
    }

    public class Badge
    {
        [JsonProperty("musicInlineBadgeRenderer")]
        public MusicInlineBadgeRenderer musicInlineBadgeRenderer { get; set; }
    }

    public class BrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string browseId { get; set; }

        [JsonProperty("browseEndpointContextSupportedConfigs")]
        public BrowseEndpointContextSupportedConfigs browseEndpointContextSupportedConfigs { get; set; }
    }

    public class BrowseEndpointContextMusicConfig
    {
        [JsonProperty("pageType")]
        public string pageType { get; set; }
    }

    public class BrowseEndpointContextSupportedConfigs
    {
        [JsonProperty("browseEndpointContextMusicConfig")]
        public BrowseEndpointContextMusicConfig browseEndpointContextMusicConfig { get; set; }
    }

    public class Button
    {
        [JsonProperty("buttonRenderer")]
        public ButtonRenderer buttonRenderer { get; set; }
    }

    public class Button4
    {
        [JsonProperty("toggleButtonRenderer")]
        public ToggleButtonRenderer toggleButtonRenderer { get; set; }

        [JsonProperty("musicPlayButtonRenderer")]
        public MusicPlayButtonRenderer musicPlayButtonRenderer { get; set; }

        [JsonProperty("menuRenderer")]
        public MenuRenderer menuRenderer { get; set; }
    }

    public class ButtonRenderer
    {
        [JsonProperty("style")]
        public string style { get; set; }

        [JsonProperty("isDisabled")]
        public bool isDisabled { get; set; }

        [JsonProperty("text")]
        public Text text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public NavigationEndpoint navigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class CheckboxRenderer
    {
        [JsonProperty("onSelectionChangeCommand")]
        public OnSelectionChangeCommand onSelectionChangeCommand { get; set; }

        [JsonProperty("checkedState")]
        public string checkedState { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class Command
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("addToToastAction")]
        public AddToToastAction addToToastAction { get; set; }
    }

    public class Content
    {
        [JsonProperty("musicPlaylistShelfRenderer")]
        public MusicPlaylistShelfRenderer musicPlaylistShelfRenderer { get; set; }

        [JsonProperty("musicResponsiveListItemRenderer")]
        public MusicResponsiveListItemRenderer musicResponsiveListItemRenderer { get; set; }

        [JsonProperty("musicResponsiveHeaderRenderer")]
        public MusicResponsiveHeaderRenderer musicResponsiveHeaderRenderer { get; set; }

        [JsonProperty("twoColumnBrowseResultsRenderer")]
        public TwoColumnBrowseResultsRenderer twoColumnBrowseResultsRenderer { get; set; }
    }

    public class Content10
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();

        [JsonProperty("musicPlayButtonRenderer")]
        public MusicPlayButtonRenderer musicPlayButtonRenderer { get; set; }

        [JsonProperty("sectionListRenderer")]
        public SectionListRenderer sectionListRenderer { get; set; }
    }

    public class Continuation
    {
        [JsonProperty("nextContinuationData")]
        public NextContinuationData nextContinuationData { get; set; }
    }

    public class DefaultIcon
    {
        [JsonProperty("iconType")]
        public string iconType { get; set; }
    }

    public class DefaultNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("modalEndpoint")]
        public ModalEndpoint modalEndpoint { get; set; }
    }

    public class DefaultServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("modalEndpoint")]
        public ModalEndpoint modalEndpoint { get; set; }
    }

    public class DefaultText
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();
    }

    public class DislikeNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("modalEndpoint")]
        public ModalEndpoint modalEndpoint { get; set; }
    }

    public class FixedColumn
    {
        [JsonProperty("musicResponsiveListItemFixedColumnRenderer")]
        public MusicResponsiveListItemFixedColumnRenderer musicResponsiveListItemFixedColumnRenderer { get; set; }
    }

    public class FlexColumn
    {
        [JsonProperty("musicResponsiveListItemFlexColumnRenderer")]
        public MusicResponsiveListItemFlexColumnRenderer musicResponsiveListItemFlexColumnRenderer { get; set; }
    }

    public class Icon
    {
        [JsonProperty("iconType")]
        public string iconType { get; set; }
    }

    public class Item
    {
        [JsonProperty("menuNavigationItemRenderer")]
        public MenuNavigationItemRenderer menuNavigationItemRenderer { get; set; }

        [JsonProperty("menuServiceItemRenderer")]
        public MenuServiceItemRenderer menuServiceItemRenderer { get; set; }

        [JsonProperty("toggleMenuServiceItemRenderer")]
        public ToggleMenuServiceItemRenderer toggleMenuServiceItemRenderer { get; set; }
    }

    public class Item2
    {
        [JsonProperty("notificationTextRenderer")]
        public NotificationTextRenderer notificationTextRenderer { get; set; }
    }

    public class LikeButtonRenderer
    {
        [JsonProperty("target")]
        public Target target { get; set; }

        [JsonProperty("likeStatus")]
        public string likeStatus { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("likesAllowed")]
        public bool likesAllowed { get; set; }

        [JsonProperty("dislikeNavigationEndpoint")]
        public DislikeNavigationEndpoint dislikeNavigationEndpoint { get; set; }

        [JsonProperty("likeCommand")]
        public LikeCommand likeCommand { get; set; }
    }

    public class LikeCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("modalEndpoint")]
        public ModalEndpoint modalEndpoint { get; set; }
    }

    public class LikeEndpoint
    {
        [JsonProperty("status")]
        public string status { get; set; }

        [JsonProperty("target")]
        public Target target { get; set; }
    }

    public class LoggingContext
    {
        [JsonProperty("vssLoggingContext")]
        public VssLoggingContext vssLoggingContext { get; set; }
    }

    public class Menu
    {
        [JsonProperty("menuRenderer")]
        public MenuRenderer menuRenderer { get; set; }
    }

    public class MenuNavigationItemRenderer
    {
        [JsonProperty("text")]
        public Text text { get; set; }

        [JsonProperty("icon")]
        public Icon icon { get; set; }

        [JsonProperty("navigationEndpoint")]
        public NavigationEndpoint navigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class MenuRenderer
    {
        [JsonProperty("items")]
        public List<Item> items { get; } = new List<Item>();

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("topLevelButtons")]
        public List<TopLevelButton> topLevelButtons { get; } = new List<TopLevelButton>();

        [JsonProperty("accessibility")]
        public Accessibility accessibility { get; set; }
    }

    public class MenuServiceItemRenderer
    {
        [JsonProperty("text")]
        public Text text { get; set; }

        [JsonProperty("icon")]
        public Icon icon { get; set; }

        [JsonProperty("serviceEndpoint")]
        public ServiceEndpoint serviceEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class Modal
    {
        [JsonProperty("modalWithTitleAndButtonRenderer")]
        public ModalWithTitleAndButtonRenderer modalWithTitleAndButtonRenderer { get; set; }
    }

    public class ModalEndpoint
    {
        [JsonProperty("modal")]
        public Modal modal { get; set; }
    }

    public class ModalWithTitleAndButtonRenderer
    {
        [JsonProperty("title")]
        public Title title { get; set; }

        [JsonProperty("content")]
        public Content content { get; set; }

        [JsonProperty("button")]
        public Button button { get; set; }
    }

    public class MultiSelectCheckbox
    {
        [JsonProperty("checkboxRenderer")]
        public CheckboxRenderer checkboxRenderer { get; set; }
    }

    public class MusicInlineBadgeRenderer
    {
        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("icon")]
        public Icon icon { get; set; }

        [JsonProperty("accessibilityData")]
        public AccessibilityData accessibilityData { get; set; }
    }

    public class MusicItemThumbnailOverlayRenderer
    {
        [JsonProperty("background")]
        public Background background { get; set; }

        [JsonProperty("content")]
        public Content content { get; set; }

        [JsonProperty("contentPosition")]
        public string contentPosition { get; set; }

        [JsonProperty("displayStyle")]
        public string displayStyle { get; set; }
    }

    public class MusicPlayButtonRenderer
    {
        [JsonProperty("playNavigationEndpoint")]
        public PlayNavigationEndpoint playNavigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("playIcon")]
        public PlayIcon playIcon { get; set; }

        [JsonProperty("pauseIcon")]
        public PauseIcon pauseIcon { get; set; }

        [JsonProperty("iconColor")]
        public object iconColor { get; set; }

        [JsonProperty("backgroundColor")]
        public int backgroundColor { get; set; }

        [JsonProperty("activeBackgroundColor")]
        public int activeBackgroundColor { get; set; }

        [JsonProperty("loadingIndicatorColor")]
        public object loadingIndicatorColor { get; set; }

        [JsonProperty("playingIcon")]
        public PlayingIcon playingIcon { get; set; }

        [JsonProperty("iconLoadingColor")]
        public int iconLoadingColor { get; set; }

        [JsonProperty("activeScaleFactor")]
        public int activeScaleFactor { get; set; }

        [JsonProperty("buttonSize")]
        public string buttonSize { get; set; }

        [JsonProperty("rippleTarget")]
        public string rippleTarget { get; set; }

        [JsonProperty("accessibilityPlayData")]
        public AccessibilityPlayData accessibilityPlayData { get; set; }

        [JsonProperty("accessibilityPauseData")]
        public AccessibilityPauseData accessibilityPauseData { get; set; }
    }

    public class MusicPlaylistShelfRenderer
    {
        [JsonProperty("playlistId")]
        public string playlistId { get; set; }

        [JsonProperty("contents")]
        public List<Content> contents { get; } = new List<Content>();

        [JsonProperty("collapsedItemCount")]
        public int collapsedItemCount { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("contentsMultiSelectable")]
        public bool contentsMultiSelectable { get; set; }
    }

    public class MusicResponsiveHeaderRenderer
    {
        [JsonProperty("thumbnail")]
        public Thumbnail thumbnail { get; set; }

        [JsonProperty("buttons")]
        public List<Button> buttons { get; } = new List<Button>();

        [JsonProperty("title")]
        public Title title { get; set; }

        [JsonProperty("subtitle")]
        public Subtitle subtitle { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("straplineTextOne")]
        public StraplineTextOne straplineTextOne { get; set; }

        [JsonProperty("straplineThumbnail")]
        public StraplineThumbnail straplineThumbnail { get; set; }

        [JsonProperty("secondSubtitle")]
        public SecondSubtitle secondSubtitle { get; set; }
    }

    public class MusicResponsiveListItemFixedColumnRenderer
    {
        [JsonProperty("text")]
        public Text text { get; set; }

        [JsonProperty("displayPriority")]
        public string displayPriority { get; set; }

        [JsonProperty("size")]
        public string size { get; set; }
    }

    public class MusicResponsiveListItemFlexColumnRenderer
    {
        [JsonProperty("text")]
        public Text text { get; set; }

        [JsonProperty("displayPriority")]
        public string displayPriority { get; set; }
    }

    public class MusicResponsiveListItemRenderer
    {
        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("thumbnail")]
        public Thumbnail thumbnail { get; set; }

        [JsonProperty("overlay")]
        public Overlay overlay { get; set; }

        [JsonProperty("flexColumns")]
        public List<FlexColumn> flexColumns { get; } = new List<FlexColumn>();

        [JsonProperty("fixedColumns")]
        public List<FixedColumn> fixedColumns { get; } = new List<FixedColumn>();

        [JsonProperty("menu")]
        public Menu menu { get; set; }

        [JsonProperty("playlistItemData")]
        public PlaylistItemData playlistItemData { get; set; }

        [JsonProperty("multiSelectCheckbox")]
        public MultiSelectCheckbox multiSelectCheckbox { get; set; }

        [JsonProperty("musicItemRendererDisplayPolicy")]
        public string musicItemRendererDisplayPolicy { get; set; }

        [JsonProperty("badges")]
        public List<Badge> badges { get; } = new List<Badge>();
    }

    public class MusicThumbnailRenderer
    {
        [JsonProperty("thumbnail")]
        public Thumbnail thumbnail { get; set; }

        [JsonProperty("thumbnailCrop")]
        public string thumbnailCrop { get; set; }

        [JsonProperty("thumbnailScale")]
        public string thumbnailScale { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class NavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("watchEndpoint")]
        public WatchEndpoint watchEndpoint { get; set; }

        [JsonProperty("browseEndpoint")]
        public BrowseEndpoint browseEndpoint { get; set; }

        [JsonProperty("modalEndpoint")]
        public ModalEndpoint modalEndpoint { get; set; }

        [JsonProperty("shareEntityEndpoint")]
        public ShareEntityEndpoint shareEntityEndpoint { get; set; }

        [JsonProperty("signInEndpoint")]
        public SignInEndpoint signInEndpoint { get; set; }

        [JsonProperty("watchPlaylistEndpoint")]
        public WatchPlaylistEndpoint watchPlaylistEndpoint { get; set; }
    }

    public class NextContinuationData
    {
        [JsonProperty("continuation")]
        public string continuation { get; set; }

        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }
    }

    public class NotificationTextRenderer
    {
        [JsonProperty("successResponseText")]
        public SuccessResponseText successResponseText { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class OnEmptyQueue
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("watchEndpoint")]
        public WatchEndpoint watchEndpoint { get; set; }
    }

    public class OnSelectionChangeCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("updateMultiSelectStateCommand")]
        public UpdateMultiSelectStateCommand updateMultiSelectStateCommand { get; set; }
    }

    public class Overlay
    {
        [JsonProperty("musicItemThumbnailOverlayRenderer")]
        public MusicItemThumbnailOverlayRenderer musicItemThumbnailOverlayRenderer { get; set; }
    }

    public class Param
    {
        [JsonProperty("key")]
        public string key { get; set; }

        [JsonProperty("value")]
        public string value { get; set; }
    }

    public class PauseIcon
    {
        [JsonProperty("iconType")]
        public string iconType { get; set; }
    }

    public class PlayIcon
    {
        [JsonProperty("iconType")]
        public string iconType { get; set; }
    }

    public class PlayingIcon
    {
        [JsonProperty("iconType")]
        public string iconType { get; set; }
    }

    public class PlaylistItemData
    {
        [JsonProperty("playlistSetVideoId")]
        public string playlistSetVideoId { get; set; }

        [JsonProperty("videoId")]
        public string videoId { get; set; }
    }

    public class PlayNavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("watchEndpoint")]
        public WatchEndpoint watchEndpoint { get; set; }
    }

    public class QueueAddEndpoint
    {
        [JsonProperty("queueTarget")]
        public QueueTarget queueTarget { get; set; }

        [JsonProperty("queueInsertPosition")]
        public string queueInsertPosition { get; set; }

        [JsonProperty("commands")]
        public List<Command> commands { get; } = new List<Command>();
    }

    public class QueueTarget
    {
        [JsonProperty("videoId")]
        public string videoId { get; set; }

        [JsonProperty("onEmptyQueue")]
        public OnEmptyQueue onEmptyQueue { get; set; }

        [JsonProperty("playlistId")]
        public string playlistId { get; set; }
    }

    public class ResponseContext
    {
        [JsonProperty("visitorData")]
        public string visitorData { get; set; }

        [JsonProperty("serviceTrackingParams")]
        public List<ServiceTrackingParam> serviceTrackingParams { get; } = new List<ServiceTrackingParam>();
    }

    public class Root
    {
        [JsonProperty("responseContext")]
        public ResponseContext responseContext { get; set; }

        [JsonProperty("contents")]
        public Contents contents { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("background")]
        public Background background { get; set; }
    }

    public class Run
    {
        [JsonProperty("text")]
        public string text { get; set; }

        [JsonProperty("navigationEndpoint")]
        public NavigationEndpoint navigationEndpoint { get; set; }
    }

    public class SecondaryContents
    {
        [JsonProperty("sectionListRenderer")]
        public SectionListRenderer sectionListRenderer { get; set; }
    }

    public class SecondSubtitle
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();
    }

    public class SectionListRenderer
    {
        [JsonProperty("contents")]
        public List<Content> contents { get; } = new List<Content>();

        [JsonProperty("continuations")]
        public List<Continuation> continuations { get; } = new List<Continuation>();

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class ServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("queueAddEndpoint")]
        public QueueAddEndpoint queueAddEndpoint { get; set; }
    }

    public class ServiceTrackingParam
    {
        [JsonProperty("service")]
        public string service { get; set; }

        [JsonProperty("params")]
        public List<Param> @params { get; } = new List<Param>();
    }

    public class ShareEntityEndpoint
    {
        [JsonProperty("serializedShareEntity")]
        public string serializedShareEntity { get; set; }

        [JsonProperty("sharePanelType")]
        public string sharePanelType { get; set; }
    }

    public class SignInEndpoint
    {
        [JsonProperty("hack")]
        public bool hack { get; set; }
    }

    public class StraplineTextOne
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();
    }

    public class StraplineThumbnail
    {
        [JsonProperty("musicThumbnailRenderer")]
        public MusicThumbnailRenderer musicThumbnailRenderer { get; set; }
    }

    public class Subtitle
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();
    }

    public class SuccessResponseText
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();
    }

    public class Tab
    {
        [JsonProperty("tabRenderer")]
        public TabRenderer tabRenderer { get; set; }
    }

    public class TabRenderer
    {
        [JsonProperty("content")]
        public Content content { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class Target
    {
        [JsonProperty("videoId")]
        public string videoId { get; set; }

        [JsonProperty("playlistId")]
        public string playlistId { get; set; }
    }

    public class Text
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();
    }

    public class Thumbnail
    {
        [JsonProperty("musicThumbnailRenderer")]
        public MusicThumbnailRenderer musicThumbnailRenderer { get; set; }

        [JsonProperty("thumbnails")]
        public List<Thumbnail10> thumbnails { get; } = new List<Thumbnail10>();
    }

    public class Thumbnail10
    {
        [JsonProperty("url")]
        public string url { get; set; }

        [JsonProperty("width")]
        public int width { get; set; }

        [JsonProperty("height")]
        public int height { get; set; }
    }

    public class Title
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();
    }

    public class ToggleButtonRenderer
    {
        [JsonProperty("isToggled")]
        public bool isToggled { get; set; }

        [JsonProperty("isDisabled")]
        public bool isDisabled { get; set; }

        [JsonProperty("defaultIcon")]
        public DefaultIcon defaultIcon { get; set; }

        [JsonProperty("toggledIcon")]
        public ToggledIcon toggledIcon { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }

        [JsonProperty("defaultNavigationEndpoint")]
        public DefaultNavigationEndpoint defaultNavigationEndpoint { get; set; }

        [JsonProperty("accessibilityData")]
        public AccessibilityData accessibilityData { get; set; }

        [JsonProperty("toggledAccessibilityData")]
        public ToggledAccessibilityData toggledAccessibilityData { get; set; }
    }

    public class ToggledAccessibilityData
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityData accessibilityData { get; set; }
    }

    public class ToggledIcon
    {
        [JsonProperty("iconType")]
        public string iconType { get; set; }
    }

    public class ToggledServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string clickTrackingParams { get; set; }

        [JsonProperty("likeEndpoint")]
        public LikeEndpoint likeEndpoint { get; set; }
    }

    public class ToggledText
    {
        [JsonProperty("runs")]
        public List<Run> runs { get; } = new List<Run>();
    }

    public class ToggleMenuServiceItemRenderer
    {
        [JsonProperty("defaultText")]
        public DefaultText defaultText { get; set; }

        [JsonProperty("defaultIcon")]
        public DefaultIcon defaultIcon { get; set; }

        [JsonProperty("defaultServiceEndpoint")]
        public DefaultServiceEndpoint defaultServiceEndpoint { get; set; }

        [JsonProperty("toggledText")]
        public ToggledText toggledText { get; set; }

        [JsonProperty("toggledIcon")]
        public ToggledIcon toggledIcon { get; set; }

        [JsonProperty("toggledServiceEndpoint")]
        public ToggledServiceEndpoint toggledServiceEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string trackingParams { get; set; }
    }

    public class TopLevelButton
    {
        [JsonProperty("likeButtonRenderer")]
        public LikeButtonRenderer likeButtonRenderer { get; set; }
    }

    public class TwoColumnBrowseResultsRenderer
    {
        [JsonProperty("secondaryContents")]
        public SecondaryContents secondaryContents { get; set; }

        [JsonProperty("tabs")]
        public List<Tab> tabs { get; } = new List<Tab>();
    }

    public class UpdateMultiSelectStateCommand
    {
        [JsonProperty("multiSelectParams")]
        public string multiSelectParams { get; set; }

        [JsonProperty("multiSelectItem")]
        public string multiSelectItem { get; set; }
    }

    public class VerticalGradient
    {
        [JsonProperty("gradientLayerColors")]
        public List<string> gradientLayerColors { get; } = new List<string>();
    }

    public class VssLoggingContext
    {
        [JsonProperty("serializedContextData")]
        public string serializedContextData { get; set; }
    }

    public class WatchEndpoint
    {
        [JsonProperty("videoId")]
        public string videoId { get; set; }

        [JsonProperty("playlistId")]
        public string playlistId { get; set; }

        [JsonProperty("params")]
        public string @params { get; set; }

        [JsonProperty("playerParams")]
        public string playerParams { get; set; }

        [JsonProperty("playlistSetVideoId")]
        public string playlistSetVideoId { get; set; }

        [JsonProperty("loggingContext")]
        public LoggingContext loggingContext { get; set; }

        [JsonProperty("watchEndpointMusicSupportedConfigs")]
        public WatchEndpointMusicSupportedConfigs watchEndpointMusicSupportedConfigs { get; set; }
    }

    public class WatchEndpointMusicConfig
    {
        [JsonProperty("musicVideoType")]
        public string musicVideoType { get; set; }
    }

    public class WatchEndpointMusicSupportedConfigs
    {
        [JsonProperty("watchEndpointMusicConfig")]
        public WatchEndpointMusicConfig watchEndpointMusicConfig { get; set; }
    }

    public class WatchPlaylistEndpoint
    {
        [JsonProperty("playlistId")]
        public string playlistId { get; set; }

        [JsonProperty("params")]
        public string @params { get; set; }
    }
}
